version: 2.1
orbs:
  node: circleci/node@5.0.2
  azure-cli: circleci/azure-cli@1.2.2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
          name: Build app
      - run:
          name: Install Azure functions tools
          command: sudo npm i -g azure-functions-core-tools@4 --unsafe-perm true
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
    docker:
      - image: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Deploy to Azure function App
          command: func azure functionapp publish $FUNCTION_APP_NAME --javascript --worker-runtime node

workflows:
  deploy-to-azure-function-app:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy if the build job has completed
          filters:
            branches:
              only: main # only deploy when on main
