jobs:
  build-and-deploy:
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install Azure functions tools
          command: sudo npm i -g azure-functions-core-tools@4 --unsafe-perm true
      - run: 
          name: Build production code
          command: npm run build:production
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Deploy to Azure function App
          command: func azure functionapp publish $FUNCTION_APP_NAME --javascript --worker-runtime node

orbs:
  azure-cli: circleci/azure-cli@1.2.2
  node: circleci/node@5.0.2
version: 2.1
workflows:
  deploy-to-azure:
    jobs:
      - build-and-deploy